/// Flutter icons OMDbcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OMDbcons
///      fonts:
///       - asset: fonts/OMDbcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OMDbcons {
  OMDbcons._();

  static const _kFontFam = 'OMDbcons';
  static const String? _kFontPkg = null;

  static const IconData back_button = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData empty_heart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
